import type { LeavePageState } from '@/types';

export const mockLeavePageState: LeavePageState = {
    status: 'ready',
    data: {
        employee: {
            name: 'Ahmed Mohammed',
            employeeCode: 'EMP-1024',
            department: 'Information Technology',
            jobTitle: 'Software Engineer',
        },

        annualLeave: {
            availableDays: 18,
            entitlementDays: 30,
            usedDays: 8,
            pendingDays: 4,
            expiringDays: 5,
            expiryDate: '2026-12-31',
        },

        sickLeave: {
            usedDays: 2,
            currentTierLabel: 'First tier',
            nextTierNote: 'Additional entitlement depends on company policy.',
        },

        pendingCounts: {
            regularCount: 2,
            shortCount: 1,
            totalCount: 3,
        },

        upcomingApprovedLeave: {
            id: 101,
            leaveTypeName: 'Annual Leave',
            startDate: '2026-11-15',
            endDate: '2026-11-19',
            durationLabel: '5 days',
            returnToWorkDate: '2026-11-22',
        },

        recentUpdates: [
            {
                id: 1,
                requestId: 1002,
                title: 'Annual leave request approved',
                occurredAt: '2026-10-08',
                statusLabel: 'Approved',
                statusTone: 'success',
                description: 'Your annual leave request has been approved.',
            },
            {
                id: 2,
                requestId: 1003,
                title: 'Sick leave request submitted',
                occurredAt: '2026-10-07',
                statusLabel: 'Pending',
                statusTone: 'warning',
                description: 'Your request is awaiting manager approval.',
            },
            {
                id: 3,
                requestId: 1004,
                title: 'Annual leave request rejected',
                occurredAt: '2026-10-01',
                statusLabel: 'Rejected',
                statusTone: 'destructive',
                description: 'The request was rejected by your manager.',
            },
        ],

        availableLeaveTypes: [
            {
                id: 1,
                label: 'Annual Leave',
                description: 'Paid leave for vacation and personal matters.',
                eligibility: {
                    kind: 'annual-balance',
                    availableDays: 18,
                    entitlementDays: 30,
                    usedDays: 8,
                    pendingDays: 4,
                },
            },
            {
                id: 2,
                label: 'Sick Leave',
                description: 'Leave for illness or medical recovery.',
                attachmentLabel: 'Medical certificate',
                eligibility: {
                    kind: 'sick-tier',
                    usedDays: 2,
                    currentTierLabel: 'First tier',
                    nextTierNote: 'Subject to your company sick leave policy.',
                },
            },
            {
                id: 3,
                label: 'Unpaid Leave',
                description: 'Leave without salary, subject to approval.',
                eligibility: {
                    kind: 'policy-unavailable',
                    message: 'Eligibility must be confirmed by HR.',
                },
            },
        ],

        regularRequests: [
            {
                id: 1001,
                leaveTypeId: 1,
                leaveTypeName: 'Annual Leave',
                startDate: '2026-11-15',
                endDate: '2026-11-19',
                durationLabel: '5 days',
                appliedAt: '2026-10-05',
                status: 'approved',
                statusLabel: 'Approved',
                statusTone: 'success',
                currentStage: 'Completed',
                reason: 'Family vacation.',
                attachments: [],
                approvalTimeline: [
                    {
                        id: 1,
                        stageName: 'Line Manager',
                        approverName: 'Mohammed Ali',
                        approverRole: 'Department Manager',
                        status: 'completed',
                        occurredAt: '2026-10-06',
                        comment: 'Approved.',
                    },
                    {
                        id: 2,
                        stageName: 'HR',
                        approverName: 'Sara Hassan',
                        approverRole: 'HR Officer',
                        status: 'completed',
                        occurredAt: '2026-10-07',
                        comment: 'Leave balance verified.',
                    },
                ],
                canCancel: false,
            },
            {
                id: 1002,
                leaveTypeId: 1,
                leaveTypeName: 'Annual Leave',
                startDate: '2026-12-01',
                endDate: '2026-12-04',
                durationLabel: '4 days',
                appliedAt: '2026-10-08',
                status: 'pending',
                statusLabel: 'Pending',
                statusTone: 'warning',
                currentStage: 'Line Manager',
                reason: 'Personal commitments.',
                attachments: [],
                approvalTimeline: [
                    {
                        id: 3,
                        stageName: 'Line Manager',
                        approverName: 'Mohammed Ali',
                        approverRole: 'Department Manager',
                        status: 'in_progress',
                    },
                    {
                        id: 4,
                        stageName: 'HR',
                        approverName: 'Sara Hassan',
                        approverRole: 'HR Officer',
                        status: 'pending',
                    },
                ],
                canCancel: true,
            },
            {
                id: 1003,
                leaveTypeId: 2,
                leaveTypeName: 'Sick Leave',
                startDate: '2026-10-12',
                endDate: '2026-10-13',
                durationLabel: '2 days',
                appliedAt: '2026-10-09',
                status: 'pending',
                statusLabel: 'Pending',
                statusTone: 'warning',
                currentStage: 'HR Review',
                reason: 'Medical recovery.',
                attachments: [
                    {
                        id: 1,
                        name: 'medical-certificate.pdf',
                        sizeLabel: '245 KB',
                        downloadAvailable: true,
                    },
                ],
                approvalTimeline: [
                    {
                        id: 5,
                        stageName: 'Line Manager',
                        approverName: 'Mohammed Ali',
                        approverRole: 'Department Manager',
                        status: 'completed',
                        occurredAt: '2026-10-09',
                    },
                    {
                        id: 6,
                        stageName: 'HR',
                        approverName: 'Sara Hassan',
                        approverRole: 'HR Officer',
                        status: 'in_progress',
                    },
                ],
                canCancel: true,
            },
            {
                id: 1004,
                leaveTypeId: 1,
                leaveTypeName: 'Annual Leave',
                startDate: '2026-10-20',
                endDate: '2026-10-22',
                durationLabel: '3 days',
                appliedAt: '2026-09-25',
                status: 'rejected',
                statusLabel: 'Rejected',
                statusTone: 'destructive',
                currentStage: 'Completed',
                reason: 'Personal travel.',
                attachments: [],
                approvalTimeline: [
                    {
                        id: 7,
                        stageName: 'Line Manager',
                        approverName: 'Mohammed Ali',
                        approverRole: 'Department Manager',
                        status: 'rejected',
                        occurredAt: '2026-09-26',
                        comment:
                            'Insufficient team coverage during these dates.',
                    },
                ],
                canCancel: false,
            },
            {
                id: 1005,
                leaveTypeId: 1,
                leaveTypeName: 'Annual Leave',
                startDate: '2026-09-10',
                endDate: '2026-09-11',
                durationLabel: '2 days',
                appliedAt: '2026-09-01',
                status: 'cancelled',
                statusLabel: 'Cancelled',
                statusTone: 'muted',
                currentStage: 'Completed',
                reason: 'Plans changed.',
                attachments: [],
                approvalTimeline: [],
                canCancel: false,
            },
        ],
    },
};
